package org.wms.dto.report;

import java.math.BigDecimal;

/**
 * Summary for client insights report.
 *
 * @param totalRevenue revenue generated by the filtered clients
 * @param totalClients number of distinct clients
 * @param totalOrders  number of sales
 * @param averageTicket average ticket among the selected clients
 */
public record ClientInsightsSummaryDto(
        BigDecimal totalRevenue,
        Long totalClients,
        Long totalOrders,
        BigDecimal averageTicket
) {
}
